# Generated by Django 5.2.14 on 2026-06-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeroporto',
            name='nome',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
