# Generated by Django 5.2.14 on 2026-06-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voos', '0002_aeroporto_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='classe_voo',
            field=models.CharField(choices=[('económica', 'Económica'), ('executiva', 'Executiva')], default='económica', max_length=20),
        ),
    ]
